### ISSUE TITLE
Bug on User Detailss

### ISSUE THREAD

**Issue by tkbdsi** [thkruz/the-enhanced-scheduling-tool#62]
A bug has been introduced into User Details: 

UsersDetails.jsx:94 Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
    at UsersDetails.jsx:94:1
    at Array.map (<anonymous>)
    at UserDetails (UsersDetails.jsx:67:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)

This corresponds to the middle line of: 

{entry.shift5?.members?.filter(u => u.id === user.id).length > 0 ? (
       <p style={{ textAlign: 'center' }}>
<Chip label={formatChipLabel(entry.shift5.shift)} color="primary" />

**Comment by tkbdsi** [comment]
@thkruz wasn't sure if you might have some insight into this one. I can go digging around to see, but wanted to check with you first.

**Comment by tkbdsi** [comment]
@thkruz Some further info: its only on initial load. I noticed this while running cypress. If the User Details are navigated too (example with a John Doe), there is the error above. Then clicking refresh will resolve the issue and everything loads. So whatever is initially undefined suddenly has data and can load it.

On the other hand, good work on that calendar display! I like how it also shows the availability.

**Comment by thkruz** [comment]
Missing question mark added.
